---
- name: Create L3 Out
  vars:
    aci_login: &aci_login
      hostname: "{{ inventory_hostname }}"
      username: "{{ user }}"
      password: "{{ password }}"
      validate_certs: False

  cisco.aci.aci_l3out:
    <<: *aci_login
    tenant: "{{ tenant }}"
    vrf: "{{ vrf }}"
    l3out: "{{ l3out }}"
    domain: "{{ dom }}"
    l3protocol: "bgp"

- name: Create Node Profile
  cisco.aci.aci_l3out_logical_node_profile:
    <<: *aci_login
    tenant: "{{ tenant }}"
    l3out: "{{ l3out }}"
    node_profile: "{{ node_prof }}"

- name: Add Nodes to Profile
  cisco.aci.aci_l3out_logical_node:
    <<: *aci_login
    tenant: "{{ tenant }}"
    l3out: "{{ l3out }}"
    node_profile: "{{ node_prof }}"
    pod_id: "{{ pod }}"
    node_id: "{{ item.node }}"
    router_id: "{{ item.router_id }}"
  loop:
    - { node: "{{ nodes[0] }}", router_id: "{{ router_ids[0] }}" }
    - { node: "{{ nodes[1] }}", router_id: "{{ router_ids[1] }}" }

