---
# vars file for l3out
tenant: ansible
vrf: prod
l3out: core
dom: l3out
node_prof: leaves
pod: 1
nodes: 
  - { id: 101, router_id: 172.31.254.13 }
  - { id: 102, router_id: 172.31.254.14 }
ifc_prof: interfaces
ifcs: 
  - { node: 101, ifc: 'eth1/45', net: '198.19.100.0/31' }
  - { node: 101, ifc: 'eth1/47', net: '198.19.100.2/31' }
  - { node: 102, ifc: 'eth1/45', net: '198.19.100.4/31' }
  - { node: 102, ifc: 'eth1/47', net: '198.19.100.6/31' }
vlan: 128
peer_asn: 65000
local_as: 65028
contract: l3out-core-default

